---

### The first task here sets up the connection between the Ansible node and the Windows target node.

- name: Add the windows vagrant host
  hosts: localhost

  tasks:
  - name: Add the windows host
    add_host:
      name: '10.75.75.101'
      groups: 'windows_host'
      ansible_user: 'vagrant'
      ansible_password: "vagrant"
      ansible_port: '5985'
      ansible_connection: 'winrm'
      ansible_winrm_server_cert_validation: 'ignore'
      ansible_winrm_operation_timeout_sec: 60
      ansible_winrm_read_timeout_sec: 70


### The following tasks are run on the target node to configure it.

- name: Configure a windows web Web-Server
  hosts: windows_host

  vars:
    win_feature_list:
    - 'NET-Framework-Features'
    - 'NET-Framework-Core'
    - 'NET-Framework-45-Features'
    - 'NET-Framework-45-Core'
    - 'NET-Framework-45-ASPNET'
    - 'Web-Server'
    - 'Web-App-Dev'
    - 'Web-Net-Ext'
    - 'Web-Net-Ext45'
    - 'NET-WCF-Services45'
    - 'Web-AppInit'
    - 'Web-Asp-Net'
    - 'Web-Asp-Net45'
    - 'Web-Mgmt-Tools'
    - 'Web-Mgmt-Console'
    - 'Web-Scripting-Tools'
### Add's FileAndStorage-Services Feature
    - 'FileAndStorage-Services'

    win_iis_webapppool_list:
    - name: 'test1'
      state: 'started'

### Add's additional IIS app pool running .NET 2.0
    win_iis_webapppool_list:
    - name: 'challenge2'
      state: 'started'
      attributes: 'managedRuntimeVersion:v2.0|autostart:true'
      
    win_file_folder_list:
    - path: 'c:\websites'
      state: 'directory'
    - path: 'c:\websites\test1'
      state: 'directory'

  roles:
    - role: win_feature
    - role: win_iis_webapppool
    - role: win_file

### Copy Files from Repo to Remote Host

- name: Copy files to remote host
  hosts: windows_host
  
  tasks: 
    - name: Copy Repo Files
      win_copy:
        src: /vagrant/files/
        dest: "C:\\websites\\test1"

### Removes Default IIS Website

- name: Remove IIS site
  hosts: windows_host
  
  tasks: 
    - name: Default IIS site
      win_iis_website:
        name: "Default Web Site"
        state: absent
              
### Create new IIS website

- name: Configure a new IIS site
  hosts: windows_host
  
  tasks: 
    - name: Test1 IIS site
      win_iis_website:
        name: "Test1"
        state: started
        port: 80
        ip: 10.75.75.101
        application_pool: "test1"
        physical_path: c:\websites\test1
        parameters: logfile.directory:c:\sites\logs|defaultDocument:index.html
      register: website
      